server:
  port: 8080

keycloak:
  enabled: true
  realm: jin
  auth-server-url: http://public.itseasy.site:10004
  ssl-required: external
  resource: springboot-test
  use-resource-role-mappings: true
  security-constraints[0]:
    authRoles[0]: user
    authRoles[1]: admin
    authRoles[2]: manager
    securityCollections[0]:
      name: test1
      patterns[0]: /test
  security-constraints[1]:
    authRoles[0]: user
    securityCollections[0]:
      name: test2
      patterns[0]: /api/*
  verify-token-audience: true
  confidential-port: 0
  bearer-only: true
  cors: true

spring:
  thymeleaf:
    enabled: true
    prefix: classpath:templates/
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDB53Dialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: swagger-ui-custom.html
    operationsSorter: method #alpha or method

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
---

spring:
  profiles:
    active: prod

---

spring:
  profiles:
    active: local